Rscript evaluate_models_constantthreshold.R 1 &
Rscript evaluate_models_constantthreshold.R 4 &
Rscript evaluate_models_constantthreshold.R 7 &
Rscript evaluate_models_constantthreshold.R 10 &
Rscript evaluate_models_constantthreshold.R 13 &
Rscript evaluate_models_constantthreshold.R 16 &
Rscript evaluate_models_constantthreshold.R 19 &
Rscript evaluate_models_constantthreshold.R 22 &
Rscript evaluate_models_constantthreshold.R 25 &
Rscript evaluate_models_constantthreshold.R 28 &
Rscript evaluate_models_constantthreshold.R 31 &
Rscript evaluate_models_constantthreshold.R 34 &
Rscript evaluate_models_constantthreshold.R 37 &
Rscript evaluate_models_constantthreshold.R 40 &
Rscript evaluate_models_constantthreshold.R 43 &
Rscript evaluate_models_constantthreshold.R 46 &
Rscript evaluate_models_constantthreshold.R 49 &
Rscript evaluate_models_constantthreshold.R 52 &
Rscript evaluate_models_constantthreshold.R 55 &
Rscript evaluate_models_constantthreshold.R 58 &
Rscript evaluate_models_constantthreshold.R 61 &
Rscript evaluate_models_constantthreshold.R 64 &
Rscript evaluate_models_constantthreshold.R 67 &
Rscript evaluate_models_constantthreshold.R 70 &
Rscript evaluate_models_constantthreshold.R 73 &
Rscript evaluate_models_constantthreshold.R 76 &
Rscript evaluate_models_constantthreshold.R 79 &
Rscript evaluate_models_constantthreshold.R 82 &
Rscript evaluate_models_constantthreshold.R 85 &
Rscript evaluate_models_constantthreshold.R 88 &
Rscript evaluate_models_constantthreshold.R 91 &
Rscript evaluate_models_constantthreshold.R 94 &
Rscript evaluate_models_constantthreshold.R 97 &
Rscript evaluate_models_constantthreshold.R 100 &
Rscript evaluate_models_constantthreshold.R 103 &
Rscript evaluate_models_constantthreshold.R 106 &
Rscript evaluate_models_constantthreshold.R 109 &
Rscript evaluate_models_constantthreshold.R 112 &
Rscript evaluate_models_constantthreshold.R 115 &
Rscript evaluate_models_constantthreshold.R 118 &
Rscript evaluate_models_constantthreshold.R 121 &
Rscript evaluate_models_constantthreshold.R 124
